package interfaz;

import dominio.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 * 
 * @author Paula Brenlla (311149) & Agustin Russo (286669)
 */
public class VentanaConsultaPorPuesto extends javax.swing.JFrame implements Observer {

    private Sistema modelo;

    //Constructor//
    /**
     * Creates new form VentanaConsultaPorPuestos
     */
    public VentanaConsultaPorPuesto(Sistema unModelo) {
        this.setModelo(unModelo);
        this.getModelo().addObserver(this);

        initComponents();

        this.update(this.modelo, this);
    }

    //Getters && Setters//
    public Sistema getModelo() {
        return modelo;
    }

    public void setModelo(Sistema unModelo) {
        this.modelo = unModelo;
    }

    //Metodos//
    @Override
    public void update(Observable o, Object obj) {
        this.tablaAPantalla();
    }

    /**
     * Borra todos los datos de la tabla y vuelve a crearla con los datos de los
 puestos registrados en el modelo.
     */
    public void tablaAPantalla() {
        tblDatosPuesto.removeAll();
        //cant filas es la cantidad de puestos, 4 columnas por la cantidad de datos.
        Object[][] datos = new Object[this.getModelo().getListaPuestos().size()][4];
        for (int i = 0; i < datos.length; i++) {
            Puesto p = this.getModelo().getListaPuestos().get(i);
            datos[i][0] = p.getIdentifiacion();
            datos[i][1] = p.getDueno().getNombre();
            datos[i][2] = p.getUbicacion();
            datos[i][3] = String.valueOf(p.getCantEmpleados());
        }

        String[] nombreCol = {"Identificación", "Dueño", "Ubicación", "Cant. Empleados"};

        //Establezco el modelo de la tabla y lo setteo
        DefaultTableModel modeloTabla = new DefaultTableModel(datos, nombreCol);
        tblDatosPuesto.setModel(modeloTabla);
        
        tblDatosPuesto.revalidate();
        tblDatosPuesto.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblScrollPane = new javax.swing.JScrollPane();
        tblDatosPuesto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mercado de Frutas y Verduras - Consulta de puestos");

        tblDatosPuesto.setEnabled(false);
        tblDatosPuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Identificación", "Nombre", "Ubicación", "Cant. Empleados"
            }
        ));
        tblScrollPane.setViewportView(tblDatosPuesto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable tblDatosPuesto;
    private javax.swing.JScrollPane tblScrollPane;
    // End of variables declaration//GEN-END:variables
}
