package interfaz;

import dominio.*;
import java.awt.Image;
import static javax.swing.JOptionPane.*;
import java.io.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Paula Brenlla (311149) & Agustin Russo (286669)
 */
public class VentanaRegistrarProducto extends javax.swing.JFrame {

    private Sistema modelo;

    /**
     * Creates new form RegistrarProducto
     *
     * @param unModelo
     */
    public VentanaRegistrarProducto(Sistema unModelo) {
        /*
        * Obtuvimos el codigo y lo adaptamos de:
        * https://stackoverflow.com/questions/29086300/how-to-change-jfilechooser-label-look-in-to-save-in-not-title
         */
        UIManager.put("FileChooser.openDialogTitleText", "Selección de archivos.");
        UIManager.put("FileChooser.lookInLabelText", "Buscar en:");
        UIManager.put("FileChooser.openButtonText", "Abrir");
        UIManager.put("FileChooser.cancelButtonText", "Cancelar");
        UIManager.put("FileChooser.fileNameLabelText", "Nombre de archivo:");
        UIManager.put("FileChooser.filesOfTypeLabelText", "Tipo de archivo:");
        UIManager.put("FileChooser.openButtonToolTipText", "Abrir archivo seleccionado");
        UIManager.put("FileChooser.cancelButtonToolTipText", "Cancelar");
        UIManager.put("FileChooser.fileNameHeaderText", "Nombre:");
        UIManager.put("FileChooser.upFolderToolTipText", "Subir");
        UIManager.put("FileChooser.homeFolderToolTipText", "Escritorio");
        UIManager.put("FileChooser.newFolderToolTipText", "Crear carpeta");
        UIManager.put("FileChooser.listViewButtonToolTipText", "Lista");
        UIManager.put("FileChooser.newFolderButtonText", "Crear carpeta");
        UIManager.put("FileChooser.renameFileButtonText", "Renombrar");
        UIManager.put("FileChooser.deleteFileButtonText", "Eliminar");
        UIManager.put("FileChooser.filterLabelText", "Tipo de archivo");
        UIManager.put("FileChooser.detailsViewButtonToolTipText", "Detalles");
        UIManager.put("FileChooser.fileSizeHeaderText", "Tamaño");
        UIManager.put("FileChooser.fileDateHeaderText", "Fecha de modificación");

        initComponents();

        this.setModelo(unModelo);
        this.resetearCampos();
    }

    //Getters && Setters//
    public void setModelo(Sistema unModelo) {
        this.modelo = unModelo;
    }

    public Sistema getModelo() {
        return modelo;
    }

    //Metodos//
    /**
     * Setea todos los parametros para crear el JFileChooser.
     *
     * @param jChooser
     */
    /**
     * Establece los valores de las cajas en nulos.
     */
    public void resetearCampos() {
        txtNombre.setText("");
        txtDescripcion.setText("");
        cboxTipoProducto.setSelectedIndex(-1);
        cboxFormaVenta.setSelectedIndex(-1);
        lblImagen.setIcon(new ImageIcon("productoSinImagen.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblTipoVenta = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        cboxTipoProducto = new javax.swing.JComboBox<>();
        cboxFormaVenta = new javax.swing.JComboBox<>();
        btnResetear = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        jChooser = new javax.swing.JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG, PNG & JPEG Images", "jpg", "png", "jpeg");
        jChooser.setFileFilter(filter);
        jChooser.setAcceptAllFileFilterUsed(false);
        jChooser.setApproveButtonText("Abrir");
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mercado de Frutas y Verduras - Registrar producto");
        getContentPane().setLayout(null);

        lblNombre.setText("Nombre:");

        lblDescripcion.setText("Descripción:");

        lblTipo.setText("Tipo:");

        lblTipoVenta.setText("Venta por:");

        cboxTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruta", "Verdura" }));

        cboxFormaVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidad", "Kilogramo" }));

        btnResetear.setText("Resetear");
        btnResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearActionPerformed(evt);
            }
        });

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(cboxTipoProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxFormaVenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResetear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cboxTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoVenta)
                    .addComponent(cboxFormaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(btnAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResetear)
                        .addGap(45, 45, 45))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(pnlDatos);
        pnlDatos.setBounds(40, 90, 280, 300);

        jChooser.setApproveButtonText("Subir");
        jChooser.setCurrentDirectory(null);
        jChooser.setDialogTitle("Selección de imagen del producto.");
        jChooser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jChooser.setName(""); // NOI18N
        String rutaCarpetaRelativa = "ImagenesOblig";
        File carpeta = new File(rutaCarpetaRelativa);
        jChooser.setCurrentDirectory(carpeta);
        jChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChooserActionPerformed(evt);
            }
        });
        getContentPane().add(jChooser);
        jChooser.setBounds(380, 40, 530, 347);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar producto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 280, 30);

        setSize(new java.awt.Dimension(972, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        //obtengo imagen
        Icon image = lblImagen.getIcon();

        String nombre = txtNombre.getText();
        if (Auxiliar.verificarLinea(nombre, 1, 50)) {

            String descripcion = txtDescripcion.getText();
            if (Auxiliar.verificarLinea(descripcion, 1, 100)) {

                if (cboxTipoProducto.getSelectedIndex() != -1) {

                    String tipoProducto = (String) cboxTipoProducto.getSelectedItem();

                    if (cboxFormaVenta.getSelectedIndex() != -1) {

                        String formaVenta = (String) cboxFormaVenta.getSelectedItem();

                        Producto prod = new Producto(nombre, descripcion, tipoProducto, formaVenta, image);

                        if (this.getModelo().agregarProductoALista(prod)) {
                            showMessageDialog(this, "El producto ha sido registrado con éxito.", "Registro exitoso", INFORMATION_MESSAGE);
                            this.resetearCampos();
                        } else {
                            showMessageDialog(this, "Ya existe un producto registrado con ese nombre.", "Error", ERROR_MESSAGE);
                            txtNombre.setText("");
                        }
                    } else { //seleccionar forma de venta
                        showMessageDialog(this, "Debe seleccionar la forma de venta del producto.", "Error", ERROR_MESSAGE);
                    }
                } else { //seleccionar tipo producto
                    showMessageDialog(this, "Debe seleccionar el tipo de producto.", "Error", ERROR_MESSAGE);
                }
            } else { //no pone descripcion
                showMessageDialog(this, "El producto debe tener una descripción de entre 1 y 100 caracteres.", "Error", ERROR_MESSAGE);
            }
        } else { //no pone nombre
            showMessageDialog(this, "El producto debe tener un nombre de entre 1 y 50 caracteres.", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
        this.resetearCampos();
    }//GEN-LAST:event_btnResetearActionPerformed

    private void jChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChooserActionPerformed
        if (evt.getActionCommand().equals(JFileChooser.APPROVE_SELECTION)) {
            //Si se clickea en aceptar del jfilechooser se elige imagen
            File f = jChooser.getSelectedFile();
            String nombreArchivo = f.getAbsolutePath();

            ImageIcon archivoIcono = new ImageIcon(nombreArchivo);

            //Se consigue la imagen y se hace el resize
            Image iconoAImagen = ((ImageIcon) archivoIcono).getImage();
            Image imagenReescalada = iconoAImagen.getScaledInstance(60, 60, Image.SCALE_SMOOTH);

            //Se muestra imagen en lbl
            lblImagen.setIcon(new ImageIcon(imagenReescalada));
        } else if (evt.getActionCommand().equals(JFileChooser.CANCEL_SELECTION)) {
            //Si se clickea cancelar en jfilechooser se reestablece imagen
            ImageIcon archivoIcono = new ImageIcon("productoSinImagen.jpg");

            Image iconoAImagen = ((ImageIcon) archivoIcono).getImage();
            Image imagenReescalada = iconoAImagen.getScaledInstance(60, 60, Image.SCALE_SMOOTH);

            //Se muestra imagen "sin imagen" en lbl
            lblImagen.setIcon(new ImageIcon(imagenReescalada));
        }
    }//GEN-LAST:event_jChooserActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnResetear;
    private javax.swing.JComboBox<String> cboxFormaVenta;
    private javax.swing.JComboBox<String> cboxTipoProducto;
    private javax.swing.JFileChooser jChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoVenta;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
