package interfaz;

import dominio.*;
import static javax.swing.JOptionPane.*;

/**
 *
 * @author Paula Brenlla (311149) & Agustin Russo (286669)
 */
public class VentanaSeleccionarVenta extends javax.swing.JFrame {

    private Sistema modelo;
    private Puesto puesto;
    private Producto producto;

    //Constructor//
    /**
     * Creates new form VentanaSeleccionarVenta
     *
     * @param unModelo
     * @param unPuesto
     * @param unProducto
     */
    public VentanaSeleccionarVenta(Sistema unModelo, Puesto unPuesto, Producto unProducto) {
        this.setModelo(unModelo);
        this.setPuesto(unPuesto);
        this.setProducto(unProducto);
        initComponents();
    }

    //Getters && Setters//
    public Sistema getModelo() {
        return modelo;
    }

    public void setModelo(Sistema unModelo) {
        this.modelo = unModelo;
    }

    public Puesto getPuesto() {
        return puesto;
    }

    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }

    public Producto getProducto() {
        return producto;
    }

    public void setProducto(Producto unProducto) {
        this.producto = unProducto;
    }

    //Metodos//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        spnPrecioUnit = new javax.swing.JSpinner();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mercado de Frutas y Verduras - Registrar venta");
        getContentPane().setLayout(null);

        jLabel1.setText("Cantidad a comprar:");

        jLabel2.setText("Precio unitario:");

        spnCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spnCantidadKeyTyped(evt);
            }
        });

        spnPrecioUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spnPrecioUnitKeyTyped(evt);
            }
        });

        btnAceptar.setText("Registrar venta");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnAceptar)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnPrecioUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnPrecioUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(16, 17, 318, 140);

        setSize(new java.awt.Dimension(389, 176));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int precio = (Integer) spnPrecioUnit.getValue();
        if (precio > 0) {

            int cantidad = (Integer) spnCantidad.getValue();
            if (cantidad > 0) {
                int numeroVenta = this.getModelo().getListaMovimientos().size() + 1;

                if (this.getPuesto().realizarVentaProducto(this.getProducto(), cantidad)) {
                    Movimiento m = new Movimiento('V', this.getProducto(), precio * cantidad, cantidad, numeroVenta, this.getPuesto());
                    this.getModelo().agregarMovimientoALista(m);

                    showMessageDialog(this, "La venta " + numeroVenta + " ha sido realizada exitosamente.", "Registro exitoso", INFORMATION_MESSAGE);
                    dispose();
                } else { //Stock < cantidad solicitada
                    showMessageDialog(this, "No hay el suficiente stock del producto seleccionado.", "Error", ERROR_MESSAGE);
                }
            } else { //no establece cantidad
                showMessageDialog(this, "La cantidad del producto debe ser mayor a 0.", "Error", ERROR_MESSAGE);
            }
        } else { //no establece precio
            showMessageDialog(this, "El precio de los productos debe ser mayor a 0.", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void spnCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnCantidadKeyTyped
        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_spnCantidadKeyTyped

    private void spnPrecioUnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnPrecioUnitKeyTyped
        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_spnPrecioUnitKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JSpinner spnPrecioUnit;
    // End of variables declaration//GEN-END:variables
}
