package interfaz;

import dominio.*;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Paula Brenlla (311149) & Agustin Russo (286669)
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form InicioSistema
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSerializar = new javax.swing.JButton();
        btnNuevoSistema = new javax.swing.JButton();
        btnCargarProds = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercado de Frutas y Verduras - Inicializacion");
        setResizable(false);
        getContentPane().setLayout(null);

        btnSerializar.setText("Datos último uso");
        btnSerializar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerializarActionPerformed(evt);
            }
        });

        btnNuevoSistema.setText("Nuevo sistema");
        btnNuevoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoSistemaActionPerformed(evt);
            }
        });

        btnCargarProds.setText("Vacio con productos");
        btnCargarProds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarProdsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnSerializar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNuevoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCargarProds, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSerializar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarProds, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 20, 570, 56);

        setSize(new java.awt.Dimension(581, 148));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoSistemaActionPerformed
        Sistema sistema = new Sistema();

        VentanaPrincipal vPrincipal = new VentanaPrincipal(sistema);
        vPrincipal.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnNuevoSistemaActionPerformed

    private void btnSerializarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerializarActionPerformed
        Sistema sistema = Sistema.desserializar();

        VentanaPrincipal vPrincipal = new VentanaPrincipal(sistema);
        vPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSerializarActionPerformed

    private void btnCargarProdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarProdsActionPerformed
        Sistema s = new Sistema();
        int contadorCargas = 0;
        ArchivoLectura arch = new ArchivoLectura("ImagenesOblig/productos.txt");
        while (arch.hayMasLineas()) {
            String linea = arch.linea();
            String[] datos = linea.split("@");

            if (Auxiliar.verificarLinea(datos[0], 1, 50)) {
                if (Auxiliar.verificarLinea(datos[1], 1, 100)) {
                    boolean tipoValido = datos[2].equalsIgnoreCase("Fruta")
                            || datos[2].equalsIgnoreCase("Verdura");

                    boolean formaValida = datos[3].equalsIgnoreCase("Unidad")
                            || datos[3].equalsIgnoreCase("Kilogramo");
                    if (tipoValido && formaValida) {
                        ImageIcon archivoIcono = new ImageIcon("ImagenesOblig/" + datos[4]);
                        //Se consigue la imagen y se hace el resize
                        Image iconoAImagen = ((ImageIcon) archivoIcono).getImage();
                        Image imagenReescalada = iconoAImagen.getScaledInstance(60, 60, Image.SCALE_SMOOTH);

                        ImageIcon image = new ImageIcon(imagenReescalada);

                        Producto p = new Producto(datos[0], datos[1], datos[2], datos[3], image);
                        if (s.agregarProductoALista(p)) {
                            contadorCargas++;
                        }
                    }
                }
            }
        }
        arch.cerrar();
        showMessageDialog(this, "Carga completa: se han cargado " + contadorCargas + " productos al sistema.", "Productos registrados.", INFORMATION_MESSAGE);

        VentanaPrincipal vPrincipal = new VentanaPrincipal(s);
        vPrincipal.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnCargarProdsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarProds;
    private javax.swing.JButton btnNuevoSistema;
    private javax.swing.JButton btnSerializar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
