package interfaz;

import dominio.*;
import java.util.*;
import static javax.swing.JOptionPane.*;

/**
 * 
 * @author Paula Brenlla (311149) & Agustin Russo (286669)
 */
public class VentanaRegistrarCompra extends javax.swing.JFrame implements Observer {

    private Sistema modelo;

    //Constructor//
    public VentanaRegistrarCompra(Sistema unModelo) {
        this.setModelo(unModelo);

        this.modelo.addObserver(this);
        initComponents();

        this.update(this.modelo, this);
    }

    //Getters && Setters//
    public Sistema getModelo() {
        return modelo;
    }

    public void setModelo(Sistema unModelo) {
        this.modelo = unModelo;
    }

    //Metodos//
    @Override
    public void update(Observable o, Object obj) {
        this.objetoAPantalla();
    }

    /**
     * Muestra en pantalla la lista de puestos y mayoristas.
     */
    public void objetoAPantalla() {
        lstPuestos.setListData(this.getModelo().getListaPuestos().toArray());
        lstMayoristas.setListData(this.getModelo().getListaMayoristas().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPuestos = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMayoristas = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mercado de Frutas y Verduras - Registrar compra");
        getContentPane().setLayout(null);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(258, 130));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(258, 130));

        lstPuestos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstPuestos);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(258, 130));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(258, 130));

        lstMayoristas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstMayoristas);

        jLabel1.setText("Lista de puestos");

        jLabel2.setText("Lista de mayoristas");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(btnAceptar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 410, 360);

        setSize(new java.awt.Dimension(458, 405));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (lstPuestos.getLeadSelectionIndex() != -1) {
            if (lstMayoristas.getLeadSelectionIndex() != -1) {
                Puesto p = (Puesto) lstPuestos.getSelectedValue();
                Mayorista m = (Mayorista) lstMayoristas.getSelectedValue();
                VentanaSeleccionarCompra vSelCompra = new VentanaSeleccionarCompra(modelo, p,m);
                vSelCompra.setVisible(true);
            } else { //si no elige mayorista
                showMessageDialog(null, "Debe seleccionar un mayorista de la lista.", "Error", ERROR_MESSAGE);
            }
        } else { //si no elige puesto
            showMessageDialog(null, "Debe seleccionar un puesto de la lista.", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstMayoristas;
    private javax.swing.JList lstPuestos;
    // End of variables declaration//GEN-END:variables
}
