package interfaz;

import dominio.Sistema;

/**
 *
 * @author Paula Brenlla (311149) & Agustin Russo (286669)
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Sistema modelo;

    public Sistema getModelo() {
        return this.modelo;
    }

    public void setModelo(Sistema unModelo) {
        this.modelo = unModelo;
    }

    /**
     * Creates new form NewApplication
     *
     * @param unModelo
     */
    public VentanaPrincipal(Sistema unModelo) {
        this.setModelo(unModelo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lblIntro = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        menuRegistros = new javax.swing.JMenu();
        itemRegProducto = new javax.swing.JMenuItem();
        itemRegDueno = new javax.swing.JMenuItem();
        itemRegPuesto = new javax.swing.JMenuItem();
        itemRegMayorista = new javax.swing.JMenuItem();
        menuMovimientos = new javax.swing.JMenu();
        itemCompra = new javax.swing.JMenuItem();
        itemVenta = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        itemConsProducto = new javax.swing.JMenuItem();
        itemConsDueno = new javax.swing.JMenuItem();
        itemConsPuesto = new javax.swing.JMenuItem();
        itemConsMayorista = new javax.swing.JMenuItem();
        itemArchivo = new javax.swing.JMenuItem();
        menuTerminar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercado de frutas y verduras");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lblIntro.setEditable(false);
        lblIntro.setColumns(20);
        lblIntro.setRows(5);
        lblIntro.setText("\n    Sistema de gestion de mercado de frutas y verduras.\n\n    Este sistema permite el manejo de los distintos productos, compras \n    y ventas, mayoristas y puestos con sus respectivos dueños.\n\n    Seleccione la opcion deseada del menu para acceder a las distintas\n    funcionalidades del sistema.\n");
        lblIntro.setFocusable(false);
        jScrollPane1.setViewportView(lblIntro);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 410, 150);

        menuRegistros.setMnemonic('f');
        menuRegistros.setText("Area de Registros");

        itemRegProducto.setMnemonic('o');
        itemRegProducto.setText("Registrar Producto");
        itemRegProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegProductoActionPerformed(evt);
            }
        });
        menuRegistros.add(itemRegProducto);

        itemRegDueno.setMnemonic('s');
        itemRegDueno.setText("Registrar Dueño de Puesto");
        itemRegDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegDuenoActionPerformed(evt);
            }
        });
        menuRegistros.add(itemRegDueno);

        itemRegPuesto.setMnemonic('a');
        itemRegPuesto.setText("Registrar Puesto");
        itemRegPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegPuestoActionPerformed(evt);
            }
        });
        menuRegistros.add(itemRegPuesto);

        itemRegMayorista.setMnemonic('x');
        itemRegMayorista.setText("Registrar Mayorista");
        itemRegMayorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegMayoristaActionPerformed(evt);
            }
        });
        menuRegistros.add(itemRegMayorista);

        menuBar.add(menuRegistros);

        menuMovimientos.setMnemonic('e');
        menuMovimientos.setText("Area de Movimientos");

        itemCompra.setMnemonic('t');
        itemCompra.setText("Registrar Compra de Producto");
        itemCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompraActionPerformed(evt);
            }
        });
        menuMovimientos.add(itemCompra);

        itemVenta.setMnemonic('y');
        itemVenta.setText("Registrar Venta de Producto");
        itemVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVentaActionPerformed(evt);
            }
        });
        menuMovimientos.add(itemVenta);

        menuBar.add(menuMovimientos);

        menuConsultas.setMnemonic('h');
        menuConsultas.setText("Area de Consultas");

        itemConsProducto.setMnemonic('c');
        itemConsProducto.setText("Consulta por Producto");
        itemConsProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsProductoActionPerformed(evt);
            }
        });
        menuConsultas.add(itemConsProducto);

        itemConsDueno.setMnemonic('a');
        itemConsDueno.setText("Consulta de Dueños");
        itemConsDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsDuenoActionPerformed(evt);
            }
        });
        menuConsultas.add(itemConsDueno);

        itemConsPuesto.setText("Consulta de Puestos");
        itemConsPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsPuestoActionPerformed(evt);
            }
        });
        menuConsultas.add(itemConsPuesto);

        itemConsMayorista.setText("Consulta de Mayoristas");
        itemConsMayorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsMayoristaActionPerformed(evt);
            }
        });
        menuConsultas.add(itemConsMayorista);

        itemArchivo.setText("Generacion de Archivo");
        itemArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemArchivoActionPerformed(evt);
            }
        });
        menuConsultas.add(itemArchivo);

        menuBar.add(menuConsultas);

        menuTerminar.setText("Terminar");
        menuTerminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTerminarMouseClicked(evt);
            }
        });
        menuBar.add(menuTerminar);

        setJMenuBar(menuBar);

        setSize(new java.awt.Dimension(466, 253));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemRegMayoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegMayoristaActionPerformed
        VentanaRegistrarMayorista vRegMayorista = new VentanaRegistrarMayorista(this.getModelo());
        vRegMayorista.setVisible(true);
    }//GEN-LAST:event_itemRegMayoristaActionPerformed

    private void menuTerminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTerminarMouseClicked
        this.getModelo().serializar();
        System.exit(0);
    }//GEN-LAST:event_menuTerminarMouseClicked

    private void itemConsDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsDuenoActionPerformed
        VentanaConsultaPorDueno vConsDueno = new VentanaConsultaPorDueno(this.getModelo());
        vConsDueno.setVisible(true);
    }//GEN-LAST:event_itemConsDuenoActionPerformed

    private void itemArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemArchivoActionPerformed
        VentanaGenerarArchivo vArchivo = new VentanaGenerarArchivo(this.getModelo());
        vArchivo.setVisible(true);
    }//GEN-LAST:event_itemArchivoActionPerformed

    private void itemRegProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegProductoActionPerformed
        VentanaRegistrarProducto vRegProducto = new VentanaRegistrarProducto(this.getModelo());
        vRegProducto.setVisible(true);
    }//GEN-LAST:event_itemRegProductoActionPerformed

    private void itemRegDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegDuenoActionPerformed
        VentanaRegistrarDueno vRegDueno = new VentanaRegistrarDueno(this.getModelo());
        vRegDueno.setVisible(true);
    }//GEN-LAST:event_itemRegDuenoActionPerformed

    private void itemRegPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegPuestoActionPerformed
        VentanaRegistrarPuesto vRegPuesto = new VentanaRegistrarPuesto(this.getModelo());
        vRegPuesto.setVisible(true);
    }//GEN-LAST:event_itemRegPuestoActionPerformed

    private void itemCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompraActionPerformed
        VentanaRegistrarCompra vRegCompra = new VentanaRegistrarCompra(this.getModelo());
        vRegCompra.setVisible(true);
    }//GEN-LAST:event_itemCompraActionPerformed

    private void itemVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVentaActionPerformed
        VentanaRegistrarVenta vRegVenta = new VentanaRegistrarVenta(modelo);
        vRegVenta.setVisible(true);
    }//GEN-LAST:event_itemVentaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.getModelo().serializar();
    }//GEN-LAST:event_formWindowClosing

    private void itemConsProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsProductoActionPerformed
        VentanaConsultaPorProducto vConsProd = new VentanaConsultaPorProducto(this.getModelo());
        vConsProd.setVisible(true);
    }//GEN-LAST:event_itemConsProductoActionPerformed

    private void itemConsPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsPuestoActionPerformed
        VentanaConsultaPorPuesto vConsPuestos = new VentanaConsultaPorPuesto(this.getModelo());
        vConsPuestos.setVisible(true);
    }//GEN-LAST:event_itemConsPuestoActionPerformed

    private void itemConsMayoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsMayoristaActionPerformed
        VentanaConsultaPorMayorista vConsMayorista = new VentanaConsultaPorMayorista(this.getModelo());
        vConsMayorista.setVisible(true);
    }//GEN-LAST:event_itemConsMayoristaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemArchivo;
    private javax.swing.JMenuItem itemCompra;
    private javax.swing.JMenuItem itemConsDueno;
    private javax.swing.JMenuItem itemConsMayorista;
    private javax.swing.JMenuItem itemConsProducto;
    private javax.swing.JMenuItem itemConsPuesto;
    private javax.swing.JMenuItem itemRegDueno;
    private javax.swing.JMenuItem itemRegMayorista;
    private javax.swing.JMenuItem itemRegProducto;
    private javax.swing.JMenuItem itemRegPuesto;
    private javax.swing.JMenuItem itemVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblIntro;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuMovimientos;
    private javax.swing.JMenu menuRegistros;
    private javax.swing.JMenu menuTerminar;
    // End of variables declaration//GEN-END:variables

}
