package interfaz;

import dominio.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paula Brenlla (311149) & Agustin Russo (286669)
 */
public class VentanaConsultaPorDueno extends javax.swing.JFrame implements Observer {

    private Sistema modelo;

    //Constructor//
    /**
     * Creates new form VentanaConsultaPorDueno
     */
    public VentanaConsultaPorDueno(Sistema unModelo) {
        this.setModelo(unModelo);
        this.getModelo().addObserver(this);

        initComponents();

        this.update(this.modelo, this);
    }

    //Getters && Setters//
    public Sistema getModelo() {
        return modelo;
    }

    public void setModelo(Sistema unModelo) {
        this.modelo = unModelo;
    }

    //Metodos//
    @Override
    public void update(Observable o, Object obj) {
        this.tablaAPantalla();
    }

    /**
     * Borra todos los datos de la tabla y vuelve a crearla con los datos de los
 duenos registrados en el modelo.
     */
    public void tablaAPantalla() {
        tblDatosDuenos.removeAll();
        //cant filas es la cantidad de duenos, 3 columnas por la cantidad de datos.
        Object[][] datos = new Object[this.getModelo().getListaDuenos().size()][3];
        for (int i = 0; i < datos.length; i++) {
            DuenoPuesto d = this.getModelo().getListaDuenos().get(i);
            datos[i][0] = d.getNombre();
            datos[i][1] = String.valueOf(d.getEdad());
            datos[i][2] = String.valueOf(d.getAnosExperiencia());
        }

        String[] nombreCol = {"Nombre", "Edad", "Años de experiencia"};

        //defino el modelo de tabla
        DefaultTableModel modeloTabla = new DefaultTableModel(datos, nombreCol);
        tblDatosDuenos.setModel(modeloTabla);

        tblDatosDuenos.revalidate();
        tblDatosDuenos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblScrollPane = new javax.swing.JScrollPane();
        tblDatosDuenos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mercado de Frutas y Verduras - Consulta de dueños");

        tblDatosDuenos.setEnabled(false);
        tblDatosDuenos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Nombre", "Edad", "Años de experiencia"}
        ));
        tblScrollPane.setViewportView(tblDatosDuenos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable tblDatosDuenos;
    private javax.swing.JScrollPane tblScrollPane;
    // End of variables declaration//GEN-END:variables
}
