package interfaz;

import dominio.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Paula Brenlla (311149) & Agustin Russo (286669)
 */
public class VentanaRegistrarVenta extends javax.swing.JFrame implements Observer {

    private Sistema modelo;
    private HashMap<JButton, Producto> mapaBotones;

    //Constructor//
    public VentanaRegistrarVenta(Sistema unModelo) {
        this.setModelo(unModelo);
        this.mapaBotones = new HashMap<>();

        this.getModelo().addObserver(this);
        initComponents();

        this.update(this.modelo, this);
    }

    //Getters && Setters//
    public Sistema getModelo() {
        return modelo;
    }

    public void setModelo(Sistema unModelo) {
        this.modelo = unModelo;
    }

    public HashMap<JButton, Producto> getMapaBotones() {
        return mapaBotones;
    }

    public void setMapaBotones(HashMap<JButton, Producto> mapaBotones) {
        this.mapaBotones = mapaBotones;
    }

    //Metodos//
    @Override
    public void update(Observable o, Object obj) {
        this.puestosAPantalla();
        if ((Puesto) cboxPuestos.getSelectedItem() != null) {
            this.productosAPantalla();
        }
    }

    /**
     * Muestra los puestos en pantalla y si el seleccionado es diferente de
     * nulo, sus productos en stock.
     */
    public void puestosAPantalla() {
        Puesto p = (Puesto) cboxPuestos.getSelectedItem();;

        cboxPuestos.setModel(new javax.swing.DefaultComboBoxModel<>(this.getModelo().getListaPuestos().toArray()));
        if (p != null) {
            cboxPuestos.setSelectedItem(p);
        }
    }

    /**
     * Muestra en forma de grid los botones de los productos con su imagen. En
     * caso de pasar el mouse sobre ellos nos muestra su nombre y si hacemos
     * click sobre ellos abre la ventana de seleccionde cantidades y precio para
     * una venta.
     */
    public void productosAPantalla() {
        pnlProductos.removeAll();
        Puesto p = (Puesto) cboxPuestos.getSelectedItem();
        //Defino que el layout van a ser 2 columnas, y cantidadDeProductos%2 las filas
        pnlProductos.setLayout(new java.awt.GridLayout(0, 3));

        //Creo e arrayList ordenado de los productos en stock
        ArrayList<Producto> listaProductos = new ArrayList<>(p.getStock().keySet());
        Collections.sort(listaProductos, new CriterioOrdenTipoProductoYNombre());

        Iterator<Producto> itProds = listaProductos.iterator();
        //Recorro la lista ordenada de productos y relaciono un boton x producto
        while (itProds.hasNext()) {
            Producto prod = itProds.next();

            JButton nuevo = new JButton(prod.getImagen());
            //setteo el texto al pasar el mouse
            nuevo.setToolTipText(prod.toString());
            //cuando hago click abro ventana
            nuevo.addActionListener(new ProcesoProducto());

            this.getMapaBotones().put(nuevo, prod);

            pnlProductos.add(nuevo);
        }
        pnlProductos.revalidate();
        pnlProductos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboxPuestos = new javax.swing.JComboBox();
        lblNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlProductos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mercado de Frutas y Verduras - Registrar venta");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Puesto:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 70, 16);

        cboxPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPuestosActionPerformed(evt);
            }
        });
        jPanel1.add(cboxPuestos);
        cboxPuestos.setBounds(80, 20, 160, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 630, 60);

        lblNombre.setVisible(false);
        getContentPane().add(lblNombre);
        lblNombre.setBounds(590, 370, 60, 20);

        pnlProductos.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setViewportView(pnlProductos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 590, 230);

        setSize(new java.awt.Dimension(667, 382));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboxPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPuestosActionPerformed
        if (cboxPuestos.getSelectedIndex() != -1) {
            productosAPantalla();
        }
    }//GEN-LAST:event_cboxPuestosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboxPuestos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlProductos;
    // End of variables declaration//GEN-END:variables

    private class ProcesoProducto implements ActionListener {

        /*
        * Obtengo los datos del producto y abro una ventana para realizar la
        * venta del producto.
        */
        @Override
        public void actionPerformed(ActionEvent e) {
            //obtengo el boton apretado, y el puesto y producto al que corresponde
            JButton botonApretado = ((JButton) e.getSource());
            Puesto puesto = (Puesto) cboxPuestos.getSelectedItem();
            Producto prod = mapaBotones.get(botonApretado);
            //abro la ventana ded ventas
            VentanaSeleccionarVenta vSelVenta = new VentanaSeleccionarVenta(modelo, puesto, prod);
            vSelVenta.setVisible(true);
        }
    }
}
